# Generated by Django 4.2.13 on 2026-01-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'mail',
                'db_table_comment': '外部创建的邮件表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100, verbose_name='文件')),
                ('schedule', models.CharField(blank=True, max_length=20, verbose_name='排期')),
                ('confirmed', models.CharField(default='待更新', max_length=20, verbose_name='是否确认')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '文章排期',
                'verbose_name_plural': '文章排期',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='邮编')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='手机')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='邮箱')),
                ('notes', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('label', models.CharField(max_length=20, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作者通讯录',
                'verbose_name_plural': '作者通讯录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='模板标题')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'db_table': 'email_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.CharField(max_length=100)),
                ('article', models.CharField(blank=True, max_length=200)),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalPeriodFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('editor_in_charge', models.CharField(blank=True, max_length=50, verbose_name='责编')),
                ('page_fee', models.CharField(default='待更新', max_length=50, verbose_name='版面费')),
                ('proof_status', models.CharField(default='待更新', max_length=50, verbose_name='校对情况')),
                ('first_second_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='一、二校编辑')),
                ('third_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='三校编辑')),
                ('final_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='终校编辑')),
                ('editor_time', models.CharField(blank=True, max_length=50, verbose_name='责编时间')),
                ('proof_time', models.CharField(blank=True, max_length=50, verbose_name='校对时间')),
                ('remarks', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('edition', models.CharField(blank=True, default='', max_length=50, verbose_name='版次')),
            ],
            options={
                'verbose_name': '第五期',
                'verbose_name_plural': '第五期',
            },
        ),
        migrations.CreateModel(
            name='JournalPeriodFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('editor_in_charge', models.CharField(blank=True, max_length=50, verbose_name='责编')),
                ('page_fee', models.CharField(default='待更新', max_length=50, verbose_name='版面费')),
                ('proof_status', models.CharField(default='待更新', max_length=50, verbose_name='校对情况')),
                ('first_second_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='一、二校编辑')),
                ('third_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='三校编辑')),
                ('final_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='终校编辑')),
                ('editor_time', models.CharField(blank=True, max_length=50, verbose_name='责编时间')),
                ('proof_time', models.CharField(blank=True, max_length=50, verbose_name='校对时间')),
                ('remarks', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('edition', models.CharField(blank=True, default='', max_length=50, verbose_name='版次')),
            ],
            options={
                'verbose_name': '第四期',
                'verbose_name_plural': '第四期',
            },
        ),
        migrations.CreateModel(
            name='JournalPeriodOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('editor_in_charge', models.CharField(blank=True, max_length=50, verbose_name='责编')),
                ('page_fee', models.CharField(default='待更新', max_length=50, verbose_name='版面费')),
                ('proof_status', models.CharField(default='待更新', max_length=50, verbose_name='校对情况')),
                ('first_second_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='一、二校编辑')),
                ('third_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='三校编辑')),
                ('final_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='终校编辑')),
                ('editor_time', models.CharField(blank=True, max_length=50, verbose_name='责编时间')),
                ('proof_time', models.CharField(blank=True, max_length=50, verbose_name='校对时间')),
                ('remarks', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('edition', models.CharField(blank=True, default='', max_length=50, verbose_name='版次')),
            ],
            options={
                'verbose_name': '第一期',
                'verbose_name_plural': '第一期',
            },
        ),
        migrations.CreateModel(
            name='JournalPeriodThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('editor_in_charge', models.CharField(blank=True, max_length=50, verbose_name='责编')),
                ('page_fee', models.CharField(default='待更新', max_length=50, verbose_name='版面费')),
                ('proof_status', models.CharField(default='待更新', max_length=50, verbose_name='校对情况')),
                ('first_second_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='一、二校编辑')),
                ('third_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='三校编辑')),
                ('final_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='终校编辑')),
                ('editor_time', models.CharField(blank=True, max_length=50, verbose_name='责编时间')),
                ('proof_time', models.CharField(blank=True, max_length=50, verbose_name='校对时间')),
                ('remarks', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('edition', models.CharField(blank=True, default='', max_length=50, verbose_name='版次')),
            ],
            options={
                'verbose_name': '第三期',
                'verbose_name_plural': '第三期',
            },
        ),
        migrations.CreateModel(
            name='JournalPeriodTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('editor_in_charge', models.CharField(blank=True, max_length=50, verbose_name='责编')),
                ('page_fee', models.CharField(default='待更新', max_length=50, verbose_name='版面费')),
                ('proof_status', models.CharField(default='待更新', max_length=50, verbose_name='校对情况')),
                ('first_second_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='一、二校编辑')),
                ('third_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='三校编辑')),
                ('final_proof_editor', models.CharField(blank=True, max_length=50, verbose_name='终校编辑')),
                ('editor_time', models.CharField(blank=True, max_length=50, verbose_name='责编时间')),
                ('proof_time', models.CharField(blank=True, max_length=50, verbose_name='校对时间')),
                ('remarks', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('edition', models.CharField(blank=True, default='', max_length=50, verbose_name='版次')),
            ],
            options={
                'verbose_name': '第二期',
                'verbose_name_plural': '第二期',
            },
        ),
        migrations.CreateModel(
            name='PeriodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_period', models.IntegerField(unique=True, verbose_name='后端期数')),
                ('display_period', models.IntegerField(verbose_name='显示期数')),
            ],
            options={
                'verbose_name': '期数映射',
                'verbose_name_plural': '期数映射',
                'ordering': ['backend_period'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='邮箱')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'db_table': 'recipient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipientGroup',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='分组名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '联系人分组',
                'verbose_name_plural': '联系人分组',
                'db_table': 'recipient_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='期次')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('workplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='工作单位')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='银行卡号')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户行')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机')),
                ('gross_pay', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='应发')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='税金')),
                ('net_pay', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='实发')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '责编信息',
                'verbose_name_plural': '责编信息',
                'db_table': 'qikan_reviewer',
                'ordering': ['-year', '-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='任务内容')),
                ('assignee', models.CharField(choices=[('孙航', '孙航'), ('李彦燕', '李彦燕'), ('陈玉忠', '陈玉忠'), ('孔源博', '孔源博'), ('新用户1', '新用户1'), ('新用户2', '新用户2')], max_length=20, verbose_name='添加人')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成')], default='in_progress', max_length=20, verbose_name='状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
                'db_table': 'qikan_todo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='更新内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '更新日志',
                'verbose_name_plural': '更新日志',
                'db_table': 'update_log',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipientGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qikan.recipientgroup', verbose_name='分组')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qikan.recipient', verbose_name='联系人')),
            ],
            options={
                'verbose_name': '联系人-分组关联',
                'verbose_name_plural': '联系人-分组关联',
                'db_table': 'recipient_group_membership',
            },
        ),
        migrations.AddField(
            model_name='recipient',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='members', through='qikan.RecipientGroupMembership', to='qikan.recipientgroup', verbose_name='所属分组'),
        ),
        migrations.AddIndex(
            model_name='recipientgroupmembership',
            index=models.Index(fields=['recipient'], name='idx_rg_recipient'),
        ),
        migrations.AddIndex(
            model_name='recipientgroupmembership',
            index=models.Index(fields=['group'], name='idx_rg_group'),
        ),
        migrations.AlterUniqueTogether(
            name='recipientgroupmembership',
            unique_together={('recipient', 'group')},
        ),
    ]
