# Generated by Django 4.2.13 on 2025-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'mail',
                'db_table_comment': '外部创建的邮件表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalPeriodFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('editor_in_charge', models.CharField(blank=True, max_length=50, verbose_name='责编')),
                ('editor', models.CharField(blank=True, max_length=50, verbose_name='编辑')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版次')),
                ('page_fee', models.CharField(blank=True, max_length=50, verbose_name='版面费')),
                ('first_proof', models.CharField(blank=True, max_length=50, verbose_name='一校')),
                ('second_proof', models.CharField(blank=True, max_length=50, verbose_name='二校')),
                ('third_proof', models.CharField(blank=True, max_length=50, verbose_name='三校')),
                ('final_proof', models.CharField(blank=True, max_length=50, verbose_name='终校')),
                ('editor_time', models.CharField(blank=True, max_length=50, verbose_name='责编时间')),
                ('first_proof_time', models.CharField(blank=True, max_length=50, verbose_name='一校时间')),
                ('second_proof_time', models.CharField(blank=True, max_length=50, verbose_name='二校时间')),
                ('third_proof_time', models.CharField(blank=True, max_length=50, verbose_name='三校时间')),
                ('final_proof_time', models.CharField(blank=True, max_length=50, verbose_name='终校时间')),
            ],
            options={
                'verbose_name': '第五期',
                'verbose_name_plural': '第五期',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalPeriodFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('editor_in_charge', models.CharField(blank=True, max_length=50, verbose_name='责编')),
                ('editor', models.CharField(blank=True, max_length=50, verbose_name='编辑')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版次')),
                ('page_fee', models.CharField(blank=True, max_length=50, verbose_name='版面费')),
                ('first_proof', models.CharField(blank=True, max_length=50, verbose_name='一校')),
                ('second_proof', models.CharField(blank=True, max_length=50, verbose_name='二校')),
                ('third_proof', models.CharField(blank=True, max_length=50, verbose_name='三校')),
                ('final_proof', models.CharField(blank=True, max_length=50, verbose_name='终校')),
                ('editor_time', models.CharField(blank=True, max_length=50, verbose_name='责编时间')),
                ('first_proof_time', models.CharField(blank=True, max_length=50, verbose_name='一校时间')),
                ('second_proof_time', models.CharField(blank=True, max_length=50, verbose_name='二校时间')),
                ('third_proof_time', models.CharField(blank=True, max_length=50, verbose_name='三校时间')),
                ('final_proof_time', models.CharField(blank=True, max_length=50, verbose_name='终校时间')),
            ],
            options={
                'verbose_name': '第四期',
                'verbose_name_plural': '第四期',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalPeriodOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('editor_in_charge', models.CharField(blank=True, max_length=50, verbose_name='责编')),
                ('editor', models.CharField(blank=True, max_length=50, verbose_name='编辑')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版次')),
                ('page_fee', models.CharField(blank=True, max_length=50, verbose_name='版面费')),
                ('first_proof', models.CharField(blank=True, max_length=50, verbose_name='一校')),
                ('second_proof', models.CharField(blank=True, max_length=50, verbose_name='二校')),
                ('third_proof', models.CharField(blank=True, max_length=50, verbose_name='三校')),
                ('final_proof', models.CharField(blank=True, max_length=50, verbose_name='终校')),
                ('editor_time', models.CharField(blank=True, max_length=50, verbose_name='责编时间')),
                ('first_proof_time', models.CharField(blank=True, max_length=50, verbose_name='一校时间')),
                ('second_proof_time', models.CharField(blank=True, max_length=50, verbose_name='二校时间')),
                ('third_proof_time', models.CharField(blank=True, max_length=50, verbose_name='三校时间')),
                ('final_proof_time', models.CharField(blank=True, max_length=50, verbose_name='终校时间')),
            ],
            options={
                'verbose_name': '第一期',
                'verbose_name_plural': '第一期',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalPeriodThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('editor_in_charge', models.CharField(blank=True, max_length=50, verbose_name='责编')),
                ('editor', models.CharField(blank=True, max_length=50, verbose_name='编辑')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版次')),
                ('page_fee', models.CharField(blank=True, max_length=50, verbose_name='版面费')),
                ('first_proof', models.CharField(blank=True, max_length=50, verbose_name='一校')),
                ('second_proof', models.CharField(blank=True, max_length=50, verbose_name='二校')),
                ('third_proof', models.CharField(blank=True, max_length=50, verbose_name='三校')),
                ('final_proof', models.CharField(blank=True, max_length=50, verbose_name='终校')),
                ('editor_time', models.CharField(blank=True, max_length=50, verbose_name='责编时间')),
                ('first_proof_time', models.CharField(blank=True, max_length=50, verbose_name='一校时间')),
                ('second_proof_time', models.CharField(blank=True, max_length=50, verbose_name='二校时间')),
                ('third_proof_time', models.CharField(blank=True, max_length=50, verbose_name='三校时间')),
                ('final_proof_time', models.CharField(blank=True, max_length=50, verbose_name='终校时间')),
            ],
            options={
                'verbose_name': '第三期',
                'verbose_name_plural': '第三期',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalPeriodTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('editor_in_charge', models.CharField(blank=True, max_length=50, verbose_name='责编')),
                ('editor', models.CharField(blank=True, max_length=50, verbose_name='编辑')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版次')),
                ('page_fee', models.CharField(blank=True, max_length=50, verbose_name='版面费')),
                ('first_proof', models.CharField(blank=True, max_length=50, verbose_name='一校')),
                ('second_proof', models.CharField(blank=True, max_length=50, verbose_name='二校')),
                ('third_proof', models.CharField(blank=True, max_length=50, verbose_name='三校')),
                ('final_proof', models.CharField(blank=True, max_length=50, verbose_name='终校')),
                ('editor_time', models.CharField(blank=True, max_length=50, verbose_name='责编时间')),
                ('first_proof_time', models.CharField(blank=True, max_length=50, verbose_name='一校时间')),
                ('second_proof_time', models.CharField(blank=True, max_length=50, verbose_name='二校时间')),
                ('third_proof_time', models.CharField(blank=True, max_length=50, verbose_name='三校时间')),
                ('final_proof_time', models.CharField(blank=True, max_length=50, verbose_name='终校时间')),
            ],
            options={
                'verbose_name': '第二期',
                'verbose_name_plural': '第二期',
                'ordering': ['id'],
            },
        ),
    ]
