# Generated by Django 4.2.13 on 2025-03-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.CharField(max_length=50, unique=True, verbose_name='稿件编号')),
                ('article', models.CharField(blank=True, max_length=50, verbose_name='文章')),
                ('amount', models.CharField(blank=True, max_length=50, verbose_name='金额')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='支付时间')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='支付方式')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='类型')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='标签')),
                ('company', models.CharField(blank=True, max_length=50, verbose_name='单位')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='识别号')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='手机')),
                ('notes', models.CharField(blank=True, max_length=50, verbose_name='备注')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票',
                'ordering': ['-id'],
            },
        ),
    ]
