# Generated by Django 4.2.13 on 2025-03-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0002_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100, verbose_name='文件')),
                ('schedule', models.CharField(blank=True, max_length=20, verbose_name='排期')),
                ('confirmed', models.CharField(default='待更新', max_length=20, verbose_name='是否确认')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '文章排期',
                'verbose_name_plural': '文章排期',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='article',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='article_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
