# Generated by Django 4.2.13 on 2025-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0003_articleschedule_alter_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalperiodfive',
            options={'verbose_name': '第五期', 'verbose_name_plural': '第五期'},
        ),
        migrations.AlterModelOptions(
            name='journalperiodfour',
            options={'verbose_name': '第四期', 'verbose_name_plural': '第四期'},
        ),
        migrations.AlterModelOptions(
            name='journalperiodone',
            options={'verbose_name': '第一期', 'verbose_name_plural': '第一期'},
        ),
        migrations.AlterModelOptions(
            name='journalperiodthree',
            options={'verbose_name': '第三期', 'verbose_name_plural': '第三期'},
        ),
        migrations.AlterModelOptions(
            name='journalperiodtwo',
            options={'verbose_name': '第二期', 'verbose_name_plural': '第二期'},
        ),
        migrations.AlterField(
            model_name='journalperiodfive',
            name='final_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='终校'),
        ),
        migrations.AlterField(
            model_name='journalperiodfive',
            name='first_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='一校'),
        ),
        migrations.AlterField(
            model_name='journalperiodfive',
            name='page_fee',
            field=models.CharField(default='待更新', max_length=50, verbose_name='版面费'),
        ),
        migrations.AlterField(
            model_name='journalperiodfive',
            name='second_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='二校'),
        ),
        migrations.AlterField(
            model_name='journalperiodfive',
            name='third_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='三校'),
        ),
        migrations.AlterField(
            model_name='journalperiodfour',
            name='final_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='终校'),
        ),
        migrations.AlterField(
            model_name='journalperiodfour',
            name='first_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='一校'),
        ),
        migrations.AlterField(
            model_name='journalperiodfour',
            name='page_fee',
            field=models.CharField(default='待更新', max_length=50, verbose_name='版面费'),
        ),
        migrations.AlterField(
            model_name='journalperiodfour',
            name='second_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='二校'),
        ),
        migrations.AlterField(
            model_name='journalperiodfour',
            name='third_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='三校'),
        ),
        migrations.AlterField(
            model_name='journalperiodone',
            name='final_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='终校'),
        ),
        migrations.AlterField(
            model_name='journalperiodone',
            name='first_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='一校'),
        ),
        migrations.AlterField(
            model_name='journalperiodone',
            name='page_fee',
            field=models.CharField(default='待更新', max_length=50, verbose_name='版面费'),
        ),
        migrations.AlterField(
            model_name='journalperiodone',
            name='second_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='二校'),
        ),
        migrations.AlterField(
            model_name='journalperiodone',
            name='third_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='三校'),
        ),
        migrations.AlterField(
            model_name='journalperiodthree',
            name='final_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='终校'),
        ),
        migrations.AlterField(
            model_name='journalperiodthree',
            name='first_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='一校'),
        ),
        migrations.AlterField(
            model_name='journalperiodthree',
            name='page_fee',
            field=models.CharField(default='待更新', max_length=50, verbose_name='版面费'),
        ),
        migrations.AlterField(
            model_name='journalperiodthree',
            name='second_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='二校'),
        ),
        migrations.AlterField(
            model_name='journalperiodthree',
            name='third_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='三校'),
        ),
        migrations.AlterField(
            model_name='journalperiodtwo',
            name='final_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='终校'),
        ),
        migrations.AlterField(
            model_name='journalperiodtwo',
            name='first_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='一校'),
        ),
        migrations.AlterField(
            model_name='journalperiodtwo',
            name='page_fee',
            field=models.CharField(default='待更新', max_length=50, verbose_name='版面费'),
        ),
        migrations.AlterField(
            model_name='journalperiodtwo',
            name='second_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='二校'),
        ),
        migrations.AlterField(
            model_name='journalperiodtwo',
            name='third_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='三校'),
        ),
    ]
