# Generated by Django 4.2.13 on 2025-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0004_alter_journalperiodfive_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_period', models.IntegerField(unique=True, verbose_name='后端期数')),
                ('display_period', models.IntegerField(verbose_name='显示期数')),
            ],
            options={
                'verbose_name': '期数映射',
                'verbose_name_plural': '期数映射',
                'ordering': ['backend_period'],
            },
        ),
    ]
