# Generated by Django 4.2.13 on 2025-03-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0005_periodmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalperiodfive',
            name='editor_edit_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalperiodfive',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalperiodfour',
            name='editor_edit_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalperiodfour',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalperiodone',
            name='editor_edit_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalperiodone',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalperiodthree',
            name='editor_edit_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalperiodthree',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalperiodtwo',
            name='editor_edit_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalperiodtwo',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
