# Generated by Django 4.2.13 on 2025-04-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0006_journalperiodfive_editor_edit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='article_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journalperiodfive',
            name='editor_edit_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='journalperiodfive',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='journalperiodfour',
            name='editor_edit_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='journalperiodfour',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='journalperiodone',
            name='editor_edit_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='journalperiodone',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='journalperiodthree',
            name='editor_edit_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='journalperiodthree',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='journalperiodtwo',
            name='editor_edit_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='journalperiodtwo',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
    ]
