# Generated by Django 4.2.13 on 2025-06-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0007_alter_invoice_article_id_alter_invoice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='邮编')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='手机')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='邮箱')),
                ('notes', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('label', models.CharField(max_length=20, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作者通讯录',
                'verbose_name_plural': '作者通讯录',
                'db_table': 'contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
