# Generated by Django 4.2.13 on 2025-06-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0008_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
