# Generated by Django 4.2.13 on 2025-06-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0009_alter_contact_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='年份')),
                ('period', models.IntegerField(verbose_name='期次')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('workplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='工作单位')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='银行卡号')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户行')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机')),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应发')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='税金')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实发')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '责编信息',
                'verbose_name_plural': '责编信息',
                'db_table': 'qikan_reviewer',
                'ordering': ['-year', '-period', '-created_at'],
            },
        ),
    ]
