# Generated by Django 4.2.13 on 2025-06-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0010_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='email',
        ),
    ]
