# Generated by Django 4.2.13 on 2025-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0011_remove_reviewer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='period',
            field=models.IntegerField(blank=True, null=True, verbose_name='期次'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年份'),
        ),
    ]
