# Generated by Django 4.2.13 on 2025-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0012_alter_reviewer_period_alter_reviewer_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='gross_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='应发'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='net_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='实发'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='税金'),
        ),
    ]
