# Generated by Django 4.2.13 on 2025-07-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0013_alter_reviewer_gross_pay_alter_reviewer_net_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalperiodfive',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodfive',
            name='editor_edit_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodfour',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodfour',
            name='editor_edit_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodone',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodone',
            name='editor_edit_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodthree',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodthree',
            name='editor_edit_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodtwo',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodtwo',
            name='editor_edit_time',
        ),
        migrations.AddField(
            model_name='journalperiodfive',
            name='final_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='终校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodfive',
            name='first_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='一校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodfive',
            name='second_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='二校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodfive',
            name='third_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='三校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodfour',
            name='final_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='终校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodfour',
            name='first_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='一校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodfour',
            name='second_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='二校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodfour',
            name='third_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='三校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodone',
            name='final_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='终校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodone',
            name='first_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='一校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodone',
            name='second_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='二校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodone',
            name='third_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='三校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodthree',
            name='final_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='终校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodthree',
            name='first_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='一校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodthree',
            name='second_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='二校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodthree',
            name='third_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='三校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodtwo',
            name='final_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='终校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodtwo',
            name='first_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='一校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodtwo',
            name='second_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='二校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodtwo',
            name='third_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='三校编辑'),
        ),
    ]
