# Generated by Django migration for merging first_proof and second_proof fields

from django.db import migrations, models


def migrate_data_forward(apps, schema_editor):
    """将原有的一校和二校数据合并到新的一、二校字段"""
    # 获取所有期刊模型
    JournalPeriodOne = apps.get_model('qikan', 'JournalPeriodOne')
    JournalPeriodTwo = apps.get_model('qikan', 'JournalPeriodTwo')
    JournalPeriodThree = apps.get_model('qikan', 'JournalPeriodThree')
    JournalPeriodFour = apps.get_model('qikan', 'JournalPeriodFour')
    JournalPeriodFive = apps.get_model('qikan', 'JournalPeriodFive')
    
    models_list = [JournalPeriodOne, JournalPeriodTwo, JournalPeriodThree, JournalPeriodFour, JournalPeriodFive]
    
    for Model in models_list:
        for journal in Model.objects.all():
            # 合并状态：优先使用一校状态，如果一校为默认值则使用二校状态
            if hasattr(journal, 'first_proof') and hasattr(journal, 'second_proof'):
                if journal.first_proof and journal.first_proof != '待更新':
                    journal.first_second_proof = journal.first_proof
                elif journal.second_proof and journal.second_proof != '待更新':
                    journal.first_second_proof = journal.second_proof
                else:
                    journal.first_second_proof = '待更新'
            
            # 合并编辑：优先使用一校编辑，如果为空则使用二校编辑
            if hasattr(journal, 'first_proof_editor') and hasattr(journal, 'second_proof_editor'):
                if journal.first_proof_editor:
                    journal.first_second_proof_editor = journal.first_proof_editor
                elif journal.second_proof_editor:
                    journal.first_second_proof_editor = journal.second_proof_editor
                else:
                    journal.first_second_proof_editor = ''
            
            # 合并时间：优先使用一校时间，如果为空则使用二校时间
            if hasattr(journal, 'first_proof_time') and hasattr(journal, 'second_proof_time'):
                if journal.first_proof_time:
                    journal.first_second_proof_time = journal.first_proof_time
                elif journal.second_proof_time:
                    journal.first_second_proof_time = journal.second_proof_time
                else:
                    journal.first_second_proof_time = ''
            
            journal.save()


def migrate_data_reverse(apps, schema_editor):
    """回滚时将合并的数据拆分回原字段"""
    # 获取所有期刊模型
    JournalPeriodOne = apps.get_model('qikan', 'JournalPeriodOne')
    JournalPeriodTwo = apps.get_model('qikan', 'JournalPeriodTwo')
    JournalPeriodThree = apps.get_model('qikan', 'JournalPeriodThree')
    JournalPeriodFour = apps.get_model('qikan', 'JournalPeriodFour')
    JournalPeriodFive = apps.get_model('qikan', 'JournalPeriodFive')
    
    models_list = [JournalPeriodOne, JournalPeriodTwo, JournalPeriodThree, JournalPeriodFour, JournalPeriodFive]
    
    for Model in models_list:
        for journal in Model.objects.all():
            # 将合并的数据拆分回一校字段
            if hasattr(journal, 'first_second_proof'):
                journal.first_proof = journal.first_second_proof
                journal.second_proof = '待更新'
            
            if hasattr(journal, 'first_second_proof_editor'):
                journal.first_proof_editor = journal.first_second_proof_editor
                journal.second_proof_editor = ''
            
            if hasattr(journal, 'first_second_proof_time'):
                journal.first_proof_time = journal.first_second_proof_time
                journal.second_proof_time = ''
            
            journal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0014_remove_journalperiodfive_editor_and_more'),
    ]

    operations = [
        # 第一步：添加新字段
        migrations.AddField(
            model_name='journalperiodfive',
            name='first_second_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='一、二校'),
        ),
        migrations.AddField(
            model_name='journalperiodfive',
            name='first_second_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='一、二校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodfive',
            name='first_second_proof_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='一、二校时间'),
        ),
        migrations.AddField(
            model_name='journalperiodfour',
            name='first_second_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='一、二校'),
        ),
        migrations.AddField(
            model_name='journalperiodfour',
            name='first_second_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='一、二校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodfour',
            name='first_second_proof_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='一、二校时间'),
        ),
        migrations.AddField(
            model_name='journalperiodone',
            name='first_second_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='一、二校'),
        ),
        migrations.AddField(
            model_name='journalperiodone',
            name='first_second_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='一、二校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodone',
            name='first_second_proof_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='一、二校时间'),
        ),
        migrations.AddField(
            model_name='journalperiodthree',
            name='first_second_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='一、二校'),
        ),
        migrations.AddField(
            model_name='journalperiodthree',
            name='first_second_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='一、二校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodthree',
            name='first_second_proof_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='一、二校时间'),
        ),
        migrations.AddField(
            model_name='journalperiodtwo',
            name='first_second_proof',
            field=models.CharField(default='待更新', max_length=50, verbose_name='一、二校'),
        ),
        migrations.AddField(
            model_name='journalperiodtwo',
            name='first_second_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='一、二校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodtwo',
            name='first_second_proof_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='一、二校时间'),
        ),
        
        # 第二步：迁移数据
        migrations.RunPython(migrate_data_forward, migrate_data_reverse),
        
        # 第三步：删除旧字段
        migrations.RemoveField(
            model_name='journalperiodfive',
            name='first_proof',
        ),
        migrations.RemoveField(
            model_name='journalperiodfive',
            name='first_proof_editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodfive',
            name='first_proof_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodfive',
            name='second_proof',
        ),
        migrations.RemoveField(
            model_name='journalperiodfive',
            name='second_proof_editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodfive',
            name='second_proof_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodfour',
            name='first_proof',
        ),
        migrations.RemoveField(
            model_name='journalperiodfour',
            name='first_proof_editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodfour',
            name='first_proof_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodfour',
            name='second_proof',
        ),
        migrations.RemoveField(
            model_name='journalperiodfour',
            name='second_proof_editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodfour',
            name='second_proof_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodone',
            name='first_proof',
        ),
        migrations.RemoveField(
            model_name='journalperiodone',
            name='first_proof_editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodone',
            name='first_proof_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodone',
            name='second_proof',
        ),
        migrations.RemoveField(
            model_name='journalperiodone',
            name='second_proof_editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodone',
            name='second_proof_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodthree',
            name='first_proof',
        ),
        migrations.RemoveField(
            model_name='journalperiodthree',
            name='first_proof_editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodthree',
            name='first_proof_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodthree',
            name='second_proof',
        ),
        migrations.RemoveField(
            model_name='journalperiodthree',
            name='second_proof_editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodthree',
            name='second_proof_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodtwo',
            name='first_proof',
        ),
        migrations.RemoveField(
            model_name='journalperiodtwo',
            name='first_proof_editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodtwo',
            name='first_proof_time',
        ),
        migrations.RemoveField(
            model_name='journalperiodtwo',
            name='second_proof',
        ),
        migrations.RemoveField(
            model_name='journalperiodtwo',
            name='second_proof_editor',
        ),
        migrations.RemoveField(
            model_name='journalperiodtwo',
            name='second_proof_time',
        ),
    ]
