# Generated by Django 4.2.13 on 2025-08-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0016_add_todo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='模板标题')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'db_table': 'email_template',
                'ordering': ['-created_at'],
            },
        ),
    ]
