# Generated by Django 4.2.13 on 2025-08-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0018_recipient'),
    ]

    def populate_groups(apps, schema_editor):
        Recipient = apps.get_model('qikan', 'Recipient')
        RecipientGroup = apps.get_model('qikan', 'RecipientGroup')
        # 直接读取 recipient 表的 group_name 列的原值（此时作为 FK 列存在同名列）
        # 创建对应的 RecipientGroup 记录，忽略 '未分组' 与空
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT DISTINCT group_name FROM recipient")
            rows = cursor.fetchall()
        for (name,) in rows:
            if not name or name.strip() == '' or name.strip() == '未分组':
                continue
            RecipientGroup.objects.get_or_create(name=name.strip())

    operations = [
        migrations.CreateModel(
            name='RecipientGroup',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='分组名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '联系人分组',
                'verbose_name_plural': '联系人分组',
                'db_table': 'recipient_group',
                'ordering': ['name'],
            },
        ),
        # 先根据旧的字符串列回填群组
        migrations.RunPython(populate_groups, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='recipient',
            name='group_name',
        ),
        migrations.AddField(
            model_name='recipient',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='qikan.recipientgroup', verbose_name='分组'),
        ),
    ]
