# Generated by Django 4.2.13 on 2025-08-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0019_recipientgroup_remove_recipient_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='group',
        ),
        migrations.CreateModel(
            name='RecipientGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qikan.recipientgroup', verbose_name='分组')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qikan.recipient', verbose_name='联系人')),
            ],
            options={
                'verbose_name': '联系人-分组关联',
                'verbose_name_plural': '联系人-分组关联',
                'db_table': 'recipient_group_membership',
            },
        ),
        migrations.AddField(
            model_name='recipient',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='members', through='qikan.RecipientGroupMembership', to='qikan.recipientgroup', verbose_name='所属分组'),
        ),
        migrations.AddIndex(
            model_name='recipientgroupmembership',
            index=models.Index(fields=['recipient'], name='idx_rg_recipient'),
        ),
        migrations.AddIndex(
            model_name='recipientgroupmembership',
            index=models.Index(fields=['group'], name='idx_rg_group'),
        ),
        migrations.AlterUniqueTogether(
            name='recipientgroupmembership',
            unique_together={('recipient', 'group')},
        ),
    ]
