# Generated by Django 4.2.13 on 2025-10-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0021_remove_journalperiodfive_final_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalperiodfive',
            name='final_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='终校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodfour',
            name='final_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='终校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodone',
            name='final_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='终校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodthree',
            name='final_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='终校编辑'),
        ),
        migrations.AddField(
            model_name='journalperiodtwo',
            name='final_proof_editor',
            field=models.CharField(blank=True, max_length=50, verbose_name='终校编辑'),
        ),
    ]
