# Generated by Django 4.2.13 on 2025-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0022_journalperiodfive_final_proof_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, verbose_name='邮箱'),
        ),
    ]
