# Generated by Django 4.2.13 on 2025-10-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikan', '0023_alter_recipient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='更新内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '更新日志',
                'verbose_name_plural': '更新日志',
                'db_table': 'update_log',
                'ordering': ['-updated_at'],
            },
        ),
    ]
